name: project_partone
description: "Gym Power - Complete Gym Management System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  firebase_core: ^2.24.1
  firebase_auth: ^4.17.1
  cloud_firestore: ^4.14.1
  uuid: ^4.5.1
  intl: ^0.20.2
  stream_transform: ^2.0.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/icon.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/icon.png