// Firebase integration updated
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFpoMQRbmbRg41O0z0ZxgwkY1RWmfsYGQ',
    appId: '1:1049193292064:web:4e83055f46708148abb745',
    messagingSenderId: '1049193292064',
    projectId: 'gym-management-system-44391',
    authDomain: 'gym-management-system-44391.firebaseapp.com',
    storageBucket: 'gym-management-system-44391.firebasestorage.app',
    measurementId: 'G-8W04J6HZGW',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbtjx_6qS1LkBlP1g0eIGyiKKgNpzwFIc',
    appId: '1:1049193292064:ios:7df68f3248bb181eabb745',
    messagingSenderId: '1049193292064',
    projectId: 'gym-management-system-44391',
    storageBucket: 'gym-management-system-44391.firebasestorage.app',
    iosBundleId: 'com.example.gymSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbtjx_6qS1LkBlP1g0eIGyiKKgNpzwFIc',
    appId: '1:1049193292064:ios:7df68f3248bb181eabb745',
    messagingSenderId: '1049193292064',
    projectId: 'gym-management-system-44391',
    storageBucket: 'gym-management-system-44391.firebasestorage.app',
    iosBundleId: 'com.example.gymSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFpoMQRbmbRg41O0z0ZxgwkY1RWmfsYGQ',
    appId: '1:1049193292064:web:64f67c07bd41a351abb745',
    messagingSenderId: '1049193292064',
    projectId: 'gym-management-system-44391',
    authDomain: 'gym-management-system-44391.firebaseapp.com',
    storageBucket: 'gym-management-system-44391.firebasestorage.app',
    measurementId: 'G-JF34GY6N7M',
  );
}
