// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqwtbk5QFCzHJ2Xt5dcC_ndSqLxGen3dk',
    appId: '1:719614742882:android:a684e0840b00492ffc9c3b',
    messagingSenderId: '719614742882',
    projectId: 'gym-power-7d814',
    storageBucket: 'gym-power-7d814.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKRWoG5hZSJIqqEvC3v5FoiEZYbWAq3_8',
    appId: '1:719614742882:ios:3137f3f01804f3b7fc9c3b',
    messagingSenderId: '719614742882',
    projectId: 'gym-power-7d814',
    storageBucket: 'gym-power-7d814.firebasestorage.app',
    iosBundleId: 'com.talha.projectPartone',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvx8PyeiXOyMAymsQumlreKyKWv0qIhKA',
    appId: '1:719614742882:web:e955321dcb98643efc9c3b',
    messagingSenderId: '719614742882',
    projectId: 'gym-power-7d814',
    authDomain: 'gym-power-7d814.firebaseapp.com',
    storageBucket: 'gym-power-7d814.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKRWoG5hZSJIqqEvC3v5FoiEZYbWAq3_8',
    appId: '1:719614742882:ios:3137f3f01804f3b7fc9c3b',
    messagingSenderId: '719614742882',
    projectId: 'gym-power-7d814',
    storageBucket: 'gym-power-7d814.firebasestorage.app',
    iosBundleId: 'com.talha.projectPartone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvx8PyeiXOyMAymsQumlreKyKWv0qIhKA',
    appId: '1:719614742882:web:89b00ca3cfedb499fc9c3b',
    messagingSenderId: '719614742882',
    projectId: 'gym-power-7d814',
    authDomain: 'gym-power-7d814.firebaseapp.com',
    storageBucket: 'gym-power-7d814.firebasestorage.app',
  );



}
